# Generated by Django 5.2.17 on 2026-09-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Yönetici"),
                    ("sales", "Satış Ekibi"),
                    ("dealer", "Bayi"),
                    ("cnc", "CNC Operatörü"),
                    ("service", "Servis Teknisyeni"),
                ],
                default="dealer",
                max_length=20,
            ),
        ),
    ]
