# Generated by Django 5.2.15 on 2026-06-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Marka",
                "verbose_name_plural": "Markalar",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("hex_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Renk",
                "verbose_name_plural": "Renkler",
            },
        ),
        migrations.CreateModel(
            name="CapModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "min_width",
                    models.DecimalField(decimal_places=2, default=100, max_digits=8),
                ),
                (
                    "max_width",
                    models.DecimalField(decimal_places=2, default=1200, max_digits=8),
                ),
                (
                    "min_height",
                    models.DecimalField(decimal_places=2, default=100, max_digits=8),
                ),
                (
                    "max_height",
                    models.DecimalField(decimal_places=2, default=2400, max_digits=8),
                ),
                (
                    "milling_offset",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kapak Modeli",
                "verbose_name_plural": "Kapak Modelleri",
            },
        ),
    ]
