# Generated by Django 5.2.17 on 2026-09-17 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Firma adı")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Yetkili"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Servis Müşterisi",
                "verbose_name_plural": "Servis Müşterileri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SMTP sunucusu"
                    ),
                ),
                ("port", models.PositiveIntegerField(default=587)),
                (
                    "security",
                    models.CharField(
                        choices=[
                            ("STARTTLS", "STARTTLS (genelde 587)"),
                            ("SSL", "SSL/TLS (genelde 465)"),
                            ("NONE", "Şifreleme yok (25)"),
                        ],
                        default="STARTTLS",
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200)),
                ("password", models.CharField(blank=True, max_length=200)),
                (
                    "from_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Gönderen adresi"
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Gönderen adı"
                    ),
                ),
                (
                    "default_to",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Varsayılan alıcı"
                    ),
                ),
                (
                    "default_cc",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Bilgi (CC)"
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        default="Servis Raporu {rapor_no} - {musteri}",
                        max_length=300,
                        verbose_name="Konu şablonu",
                    ),
                ),
                (
                    "attach_photos",
                    models.BooleanField(default=True, verbose_name="Fotoğrafları ekle"),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("company_address", models.TextField(blank=True)),
                ("company_phone", models.CharField(blank=True, max_length=50)),
                ("company_email", models.EmailField(blank=True, max_length=254)),
                ("company_web", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mail Ayarları",
                "verbose_name_plural": "Mail Ayarları",
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Makine adı / tipi"),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Marka"),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "serial_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Seri no",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Üretim yılı"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Konum / hat"
                    ),
                ),
                (
                    "install_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kurulum tarihi"
                    ),
                ),
                (
                    "warranty_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Garanti bitişi"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="service.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Makine",
                "verbose_name_plural": "Makineler",
                "ordering": ["customer__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Rapor no"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ARIZA", "Arıza"),
                            ("PERIYODIK_BAKIM", "Periyodik Bakım"),
                            ("KURULUM", "Kurulum"),
                            ("DEVREYE_ALMA", "Devreye Alma"),
                            ("REVIZYON", "Revizyon"),
                            ("KESIF", "Keşif"),
                            ("EGITIM", "Eğitim"),
                            ("GARANTI", "Garanti"),
                        ],
                        default="ARIZA",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TASLAK", "Taslak"),
                            ("ACIK", "Açık"),
                            ("COZULDU", "Çözüldü"),
                            ("GECICI_COZUM", "Geçici Çözüm"),
                            ("PARCA_BEKLIYOR", "Parça Bekliyor"),
                            ("TEKRAR_ZIYARET", "Tekrar Ziyaret Gerekli"),
                        ],
                        default="ACIK",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("DUSUK", "Düşük"),
                            ("NORMAL", "Normal"),
                            ("YUKSEK", "Yüksek"),
                            ("KRITIK", "Kritik / Duruş"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("service_date", models.DateField(verbose_name="Servis tarihi")),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "travel_km",
                    models.DecimalField(decimal_places=1, default=0, max_digits=8),
                ),
                (
                    "fault_description",
                    models.TextField(blank=True, verbose_name="Arıza / talep tanımı"),
                ),
                (
                    "fault_cause",
                    models.TextField(blank=True, verbose_name="Arıza nedeni"),
                ),
                (
                    "work_done",
                    models.TextField(blank=True, verbose_name="Yapılan işlem"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Öneriler"),
                ),
                ("technician_name", models.CharField(blank=True, max_length=150)),
                (
                    "customer_rep",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Müşteri yetkilisi"
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="servis/imzalar/"
                    ),
                ),
                (
                    "next_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Sonraki bakım"
                    ),
                ),
                ("mailed_to", models.CharField(blank=True, max_length=500)),
                ("mailed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="service.customer",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="service.machine",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Servis Raporu",
                "verbose_name_plural": "Servis Raporları",
                "ordering": ["-service_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ServicePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="servis/fotograflar/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("ARIZA", "Arıza"),
                            ("ONCESI", "İşlem Öncesi"),
                            ("SONRASI", "İşlem Sonrası"),
                            ("PARCA", "Parça"),
                            ("ETIKET", "Makine Etiketi"),
                            ("DIGER", "Diğer"),
                        ],
                        default="ARIZA",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="service.servicereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servis Fotoğrafı",
                "verbose_name_plural": "Servis Fotoğrafları",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("MEKANIK", "Mekanik"),
                            ("ELEKTRIK", "Elektrik"),
                            ("ELEKTRONIK", "Elektronik"),
                            ("PNOMATIK", "Pnömatik"),
                            ("HIDROLIK", "Hidrolik"),
                            ("YAZILIM", "Yazılım / PLC"),
                            ("KALIBRASYON", "Kalibrasyon"),
                            ("OTOMASYON", "Otomasyon"),
                            ("TEMIZLIK", "Temizlik / Yağlama"),
                            ("DIGER", "Diğer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("work", models.TextField(blank=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="service.servicereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çalışılan Bölüm",
                "verbose_name_plural": "Çalışılan Bölümler",
            },
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit", models.CharField(default="adet", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TAKILDI", "Takıldı"),
                            ("GEREKLI", "Gerekli"),
                            ("SIPARIS", "Sipariş Edilecek"),
                            ("TEKLIF", "Teklif Verilecek"),
                        ],
                        default="TAKILDI",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="service.servicereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yedek Parça",
                "verbose_name_plural": "Yedek Parçalar",
                "ordering": ["id"],
            },
        ),
    ]
