# Generated by Django 5.2.17 on 2026-09-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usd_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "eur_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("rates_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "show_charge_on_pdf",
                    models.BooleanField(
                        default=False, verbose_name="Servis bedeli PDF raporda görünsün"
                    ),
                ),
                (
                    "overdue_grace_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Gecikme uyarısı için tolerans (gün)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cari Ayarları",
                "verbose_name_plural": "Cari Ayarları",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("YAKIT", "Yakıt"),
                            ("KONAKLAMA", "Konaklama / Otel"),
                            ("YEMEK", "Yemek"),
                            ("YOL", "Otoyol / Köprü"),
                            ("OTOPARK", "Otopark"),
                            ("ULASIM", "Ulaşım (uçak, otobüs)"),
                            ("MALZEME", "Malzeme / Sarf"),
                            ("KARGO", "Kargo"),
                            ("ARAC", "Araç Bakım / Lastik"),
                            ("DIGER", "Diğer"),
                        ],
                        default="YAKIT",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası (₺)"),
                            ("USD", "Dolar ($)"),
                            ("EUR", "Euro (€)"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=1, max_digits=10),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Miktar (yakıt için litre)",
                    ),
                ),
                (
                    "billable",
                    models.BooleanField(
                        default=False, verbose_name="Müşteriye yansıtılacak"
                    ),
                ),
                (
                    "receipt",
                    models.ImageField(
                        blank=True, null=True, upload_to="servis/fisler/"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="service.customer",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="service.servicereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Masraf",
                "verbose_name_plural": "Masraflar",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BORC", "Borç / Hakediş"),
                            ("TAHSILAT", "Tahsilat"),
                            ("IADE", "İade / İskonto"),
                        ],
                        default="BORC",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası (₺)"),
                            ("USD", "Dolar ($)"),
                            ("EUR", "Euro (€)"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        max_digits=10,
                        verbose_name="TL kuru",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "document_no",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Belge no"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Vade"),
                ),
                (
                    "promised_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Söz verilen ödeme tarihi"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("NAKIT", "Nakit"),
                            ("HAVALE", "Havale / EFT"),
                            ("KREDI_KARTI", "Kredi Kartı"),
                            ("CEK", "Çek"),
                            ("SENET", "Senet"),
                            ("DIGER", "Diğer"),
                        ],
                        default="NAKIT",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="service.customer",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="service.servicereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cari Hareket",
                "verbose_name_plural": "Cari Hareketler",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
