# Generated by Django 5.2.17 on 2026-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_financesettings_expense_ledgerentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="financesettings",
            name="rate_date_label",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Kur bülten tarihi"
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="rate_source",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Kur kaynağı"
            ),
        ),
    ]
