# Generated by Django 5.2.17 on 2026-09-18 14:39

from django.db import migrations, models


def set_existing_charge_kind(apps, schema_editor):
    """Mevcut rapora bağlı borç kalemleri servis bedelidir."""
    LedgerEntry = apps.get_model("service", "LedgerEntry")
    LedgerEntry.objects.filter(report__isnull=False, type="BORC", kind="DIGER").update(kind="SERVIS")


def unset_charge_kind(apps, schema_editor):
    LedgerEntry = apps.get_model("service", "LedgerEntry")
    LedgerEntry.objects.filter(kind="SERVIS").update(kind="DIGER")


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_financesettings_rate_date_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financesettings",
            name="expenses_billable_by_default",
            field=models.BooleanField(
                default=True,
                verbose_name="Masraflar varsayılan olarak müşteriye yansıtılsın",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SERVIS", "Servis bedeli"),
                    ("MASRAF", "Yansıtılan masraf"),
                    ("DIGER", "Diğer"),
                ],
                default="DIGER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="billable",
            field=models.BooleanField(
                default=True, verbose_name="Müşteriye yansıtılacak"
            ),
        ),
        migrations.RunPython(set_existing_charge_kind, unset_charge_kind),
    ]
