# Generated by Django 5.2.15 on 2026-06-11 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NestingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "plate_width",
                    models.DecimalField(
                        decimal_places=2, help_text="Plaka genişliği (mm)", max_digits=8
                    ),
                ),
                (
                    "plate_height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Plaka yüksekliği (mm)",
                        max_digits=8,
                    ),
                ),
                (
                    "kerf",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.0,
                        help_text="Freze çapı / takım boşluğu (mm)",
                        max_digits=5,
                    ),
                ),
                (
                    "tool_diameter",
                    models.DecimalField(
                        decimal_places=2,
                        default=6.0,
                        help_text="Freze takım çapı (mm)",
                        max_digits=5,
                    ),
                ),
                (
                    "feed_rate",
                    models.IntegerField(
                        default=6000, help_text="İlerleme hızı (mm/dak)"
                    ),
                ),
                (
                    "spindle_speed",
                    models.IntegerField(default=18000, help_text="Devir (RPM)"),
                ),
                (
                    "cut_depth",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="Kesim derinliği (mm)",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Hazırlanıyor"), ("done", "Tamamlandı")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("nesting_result", models.JSONField(blank=True, null=True)),
                (
                    "efficiency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Plaka kullanım verimliliği %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(
                        blank=True, related_name="nesting_jobs", to="orders.order"
                    ),
                ),
            ],
            options={
                "verbose_name": "CNC Nesting İşi",
                "verbose_name_plural": "CNC Nesting İşleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NestingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "piece_index",
                    models.IntegerField(help_text="Aynı kalemden kaçıncı adet"),
                ),
                ("x", models.DecimalField(decimal_places=2, max_digits=8)),
                ("y", models.DecimalField(decimal_places=2, max_digits=8)),
                ("width", models.DecimalField(decimal_places=2, max_digits=8)),
                ("height", models.DecimalField(decimal_places=2, max_digits=8)),
                ("rotated", models.BooleanField(default=False)),
                (
                    "plate_index",
                    models.IntegerField(
                        default=0, help_text="Kaçıncı plaka (0'dan başlar)"
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orderitem",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placed_items",
                        to="cnc.nestingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["plate_index", "y", "x"],
            },
        ),
    ]
