# Generated by Django 5.2.15 on 2026-06-19 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnc", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrillPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Parça adı", max_length=200)),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DWD proje adı",
                        max_length=200,
                    ),
                ),
                ("order_no", models.CharField(blank=True, default="", max_length=100)),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, help_text="Parça boyu X (mm)", max_digits=9
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, help_text="Parça eni Y (mm)", max_digits=9
                    ),
                ),
                (
                    "thickness",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        help_text="Kalınlık (mm)",
                        max_digits=6,
                    ),
                ),
                ("material", models.CharField(blank=True, default="", max_length=100)),
                ("application", models.CharField(default="IngoMachine", max_length=50)),
                ("application_version", models.CharField(default="2.0", max_length=20)),
                (
                    "panel_attrib",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Panel düzeyi ham nitelikler",
                    ),
                ),
                (
                    "machinings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Operasyon listesi (delik/kanal)",
                    ),
                ),
                ("edge_group_attrib", models.JSONField(blank=True, default=dict)),
                ("edges", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("imported", "İçe aktarıldı"),
                            ("manual", "Elle oluşturuldu"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drill_panels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drill_panels",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delme Paneli",
                "verbose_name_plural": "Delme Panelleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
